dag: true

steps:
  - id: "deploy-service-role-stack"
    name: ":aws-iam: :cloudformation:"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    command: .buildkite/steps/deploy-service-role-stack.sh

  - id: "packer-linux-amd64"
    name: ":packer: :linux: AMD64"
    command: .buildkite/steps/packer.sh linux
    timeout_in_minutes: 60
    retry: { automatic: { limit: 3 } }
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - id: "launch-linux-amd64"
    name: ":cloudformation: :linux: AMD64 Launch"
    command: .buildkite/steps/launch.sh linux
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "build/aws-stack.yml"
    depends_on:
      - "packer-linux-amd64"
      - "deploy-service-role-stack"

  - id: "test-linux-amd64"
    name: ":cloudformation: :linux: AMD64 Test"
    command:
      - git --version
      - goss validate --format documentation
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-linux-amd64-${BUILDKITE_BUILD_NUMBER}"
      queue: "testqueue-linux-amd64-${BUILDKITE_BUILD_NUMBER}"
    depends_on:
      - "launch-linux-amd64"

  - id: test-linux-amd64-docker-compose
    name: ":cloudformation: :linux::docker: AMD64 Test Docker Compose"
    timeout_in_minutes: 5
    agents:
      stack: buildkite-aws-stack-test-linux-amd64-${BUILDKITE_BUILD_NUMBER}
      queue: testqueue-linux-amd64-${BUILDKITE_BUILD_NUMBER}
    env:
      BUILDKIT_PROGRESS: plain
    plugins:
      - docker-compose#v3.7.0:
          run: app_with_deps
          config: tests/docker-compose.yaml
    depends_on:
      - launch-linux-amd64

  - id: test-linux-amd64-docker-build
    name: ":cloudformation: :linux::docker: AMD64 Test Docker Buildx"
    timeout_in_minutes: 5
    command: docker buildx build -f tests/Dockerfile.postgres --progress=plain -t buildkite-postgres:latest tests
    agents:
      stack: buildkite-aws-stack-test-linux-amd64-${BUILDKITE_BUILD_NUMBER}
      queue: testqueue-linux-amd64-${BUILDKITE_BUILD_NUMBER}
    depends_on:
      - launch-linux-amd64

  - id: "delete-linux-amd64"
    name: ":cloudformation: :linux: AMD64 Delete"
    command: .buildkite/steps/delete.sh linux amd64
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    depends_on:
      - test-linux-amd64
      - test-linux-amd64-docker-compose
      - test-linux-amd64-docker-build

  - id: "delete-service-role-stack"
    name: ":aws-iam: :cloudformation: Delete"
    command: .buildkite/steps/delete-service-role-stack.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    depends_on:
      - delete-linux-amd64

  - id: "cleanup"
    name: "Cleanup"
    command: .buildkite/steps/cleanup.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    depends_on:
      - delete-linux-amd64
